version: "3"
services:
  ffmpeg_cuda0:
    container_name: ffmpeg_cuda0
#    volumes:
#      - /home/user01/Docker/04_stream/record/:/root/record
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        TZ: "Asia/Seoul"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu, utility, compute, video]

#=====================================================================================================================================================================================

  rtsp_srv0:
    container_name: rtsp_srv0
    restart: always
    image: aler9/rtsp-simple-server:v0.21.1
    network_mode: host       # important for WebRTC, HomeKit, UDP cameras
    privileged: true         # only for FFmpeg hardware transcoding
    environment:
      TZ: "Asia/Seoul"