version: "3"
services:
  ffmpeg_cuda0:
    container_name: 04_FFController
#    volumes:
#      - /home/user01/Docker/04_stream/record/:/root/record
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
        TZ: "Asia/Seoul"
    ports:
      - "15000:5000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu, utility, compute, video]

#=====================================================================================================================================================================================

  rtsp_srv0:
    container_name: 04_rtsp_srv0
    image: aler9/rtsp-simple-server:v0.21.1
    network_mode: host
    privileged: true
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /home/user01/Docker/04_FFController/rtsp-simple-server.yml:/rtsp-simple-server.yml
